apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    env: prod
    owner: Radik
spec:
  selector: 
    project: go-serv
  ports:
    - name: app-listener
      protocol: TCP
      port: 8000
      targetPort: 3000
  type: LoadBalancer
