pipeline {
    agent any
    stages {
        stage ('Pull and run docker image') {
            steps {
                sh 'docker pull cotelette/go-lang-app:latest'
                sh 'docker run -p 8000:3000 --rm -dit cotelette/go-lang-app:latest'
            }
        }
    }
}
